name: Build Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Show Repository
        shell: bash
        run: |
         pwd
          ls -R

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Client Dependencies
        working-directory: client
        run: npm install

      - name: Build Electron App
        working-directory: client
        run: npm run dist

      - name: Skip Upload
        run: echo "Skipping artifact upload"
